LOOP_FOREVER = -1

GLOBAL_KILL_KEY = "<ctrl>+<shift>+<alt>+<f12>"

MOUSE_BUTTONS = {"left", "right", "middle"}

TAP_DURATION_MIN = 0.04
TAP_DURATION_MAX = 0.08

POSITION_JITTER_PX = 5

SMOOTH_STEPS = 20
SMOOTH_STEP_DELAY = 0.01

SCHEDULER_TICK = 0.05
COLOR_POLL_INTERVAL = 1.0
